### ISSUE TITLE
Demo app improvements

### ISSUE THREAD

**Issue by ltomuta** [microsoft/rate-my-app#3]
- add About page with some basic T&C (as mentioned in the feedback strings)
- show value of counters

**Comment by hamishwillee** [comment]
It is definitely a good idea to allow counters to be reset so that manual rating through about page or elsewhere is supported.

I'm not completely convinced that we can/should provide a one-size fits all About page in the library (if that is what you are proposing). I guess it doesn't hurt to provide a basic implementation that we think most people will use.

If we do, then there is a fairly "standardised" approach in this article [Advanced_About_Page_for_Windows_Phone_apps](http://developer.nokia.com/Community/Wiki/Advanced_About_Page_for_Windows_Phone_apps) which uses Cimbalino to get details like author and app version from the app manifest.

**Comment by ltomuta** [comment]
I was thinking about adding these updates to the demo apps only, not part of the library.

**Comment by hamishwillee** [comment]
Sounds good, but IMO we should still update the guide to cover this aspect of the rating an app. I'd still borrow the code from the Advanced About Page.

regards
H

**Comment by ltomuta** [comment]
It would be probably better to wait with the documentation update until we have an implementation for #2.

**Comment by ltomuta** [comment]
The internal state of the rate my app component is now displayed in the demo app for WP8 ( debug build ). No docs update needed.

**Comment by ltomuta** [comment]
Done in WP8 XAML variant.
